#ifndef PROJECT_H_INCLUDED
#define PROJECT_H_INCLUDED

typedef enum{
   STATE_START,
   STATE_WAIT_10,
   STATE_WAIT_30,
   STATE_FORWARD,
   STATE_TORQUE_P,
   STATE_TORQUE_N,
   STATE_ACTIVATE,
   STATE_RIGHT,
   STATE_LEFT,
   STATE_DEACTIVATE,
   STATE_BACK

} State;

#endif // PROJECT_H_INCLUDED
